"""
Database layer. PostgreSQL connection and persistence helpers.
"""

from .connection import get_connection, init_db
from .cleanup import run_retention_cleanup
from .quality import run_data_quality_checks
from .graph import (
    add_asin_relationship,
    get_relationships_for_asin_ids,
    list_relationships,
    persist_related_sponsored_candidates,
)
from .seeds import (
    add_seed,
    get_enabled_seed_urls,
    list_seeds,
    set_seed_enabled,
)
from .category_seeds import (
    add_category_seed,
    get_active_category_seed_urls,
    get_category_seed,
    get_ready_category_seeds,
    list_category_seeds,
    set_category_seed_active,
    update_category_seed_scan,
)
from .keyword_seeds import (
    add_keyword_seed,
    get_active_keyword_seeds,
    get_keyword_seed,
    get_ready_keyword_seeds,
    list_keyword_seeds,
    set_keyword_seed_active,
    update_keyword_seed_scan,
)
from .notification_rules import (
    create_notification_rule,
    evaluate_rule,
    get_notification_rule,
    list_notification_rules,
)
from .saved_views import (
    create_saved_view,
    get_saved_view,
    list_saved_views,
    update_saved_view,
)
from .watchlists import (
    add_watchlist_item,
    create_watchlist,
    get_watchlist,
    list_watchlist_items,
    list_watchlists,
    remove_watchlist_item,
)
from .workspace import (
    create_workspace,
    create_user,
    get_workspace,
    get_users_for_workspace,
    list_workspaces,
    list_asins_by_workspace,
)
from .plans import (
    create_plan,
    get_plan,
    get_workspace_plan,
    list_plans,
    set_workspace_plan,
)
from .workspace_api_keys import (
    create_workspace_api_key,
    list_workspace_api_keys,
    validate_workspace_api_key,
)
from .usage import (
    get_usage_summary,
    get_usage_summary_for_workspace,
    record_usage,
)
from .quota import (
    check_quota,
    check_quota_and_raise,
    get_workspace_quota,
    list_workspace_quotas,
    set_workspace_quota,
    QuotaExceededError,
)
from .audit import list_audit_logs, record_audit
from .billing import (
    get_billable_events_summary,
    record_billable_event,
    record_usage_summary_billable,
)
from .worker_queue import (
    dequeue_next,
    enqueue_job,
    get_job,
    get_job_counts_for_workspace,
    get_queue_metrics,
    list_jobs,
    mark_job_completed,
    mark_job_failed,
    run_job,
    run_job_async,
    schedule_retry_or_mark_failed,
)
from .trend_persistence import (
    get_trend_result_history,
    get_trend_result_latest,
    persist_trend_result,
    TARGET_TYPE_ASIN,
    TARGET_TYPE_CLUSTER,
)
from .cluster_cache import (
    get_cluster_cache,
    get_cluster_cache_freshness,
    invalidate_cluster_cache,
    save_cluster_cache,
)
from .discovery_storage import (
    get_discovery_context_for_asin,
    get_discovery_result_latest,
    get_discovery_results,
    save_discovery_result,
    SOURCE_TYPE_AUTOMATED,
    SOURCE_TYPE_CATEGORY,
    SOURCE_TYPE_GRAPH,
    SOURCE_TYPE_KEYWORD,
)
from .asin_keyword_graph import (
    add_asin_keyword_edge,
    add_asin_keyword_edges_bulk,
    get_keywords_for_asin,
    get_asins_for_keyword,
    sync_edges_from_discovery_result,
    SOURCE_KEYWORD_SCAN,
    SOURCE_DISCOVERY_RESULT,
    SOURCE_EXPANSION,
)
from .opportunity_alerts import (
    save_opportunity_alert,
    list_opportunity_alerts,
    set_opportunity_alert_read,
)
from .tenant_analytics_snapshots import (
    save_tenant_snapshot,
    get_latest_snapshot,
    get_snapshot_history,
)
from .workspace_intelligence_snapshots import (
    save_workspace_intelligence_snapshot,
    get_latest_workspace_intelligence_snapshot,
    list_workspace_intelligence_snapshots,
)
from .workspace_configuration import (
    get_workspace_configuration as get_workspace_configuration_row,
    upsert_workspace_configuration as upsert_workspace_configuration_row,
)
from .workspace_portfolio import (
    add_workspace_portfolio_item,
    archive_workspace_portfolio_item,
    get_workspace_portfolio_item_by_key,
    get_workspace_portfolio_summary,
    list_workspace_portfolio_items,
)
from .workspace_alert_preferences import (
    get_workspace_alert_preferences as get_workspace_alert_preferences_row,
    upsert_workspace_alert_preferences as upsert_workspace_alert_preferences_row,
)
from .workspace_activity_log import (
    create_workspace_activity_event as create_workspace_activity_event_row,
    list_workspace_activity_events,
    get_workspace_activity_summary,
)
from .autonomous_research_audit import (
    save_autonomous_run_audit,
    get_audit_for_run,
    get_audit_trail as get_autonomous_audit_trail,
)
from .opportunity_memory import (
    record_opportunity_seen,
    get_opportunity_memory,
    get_opportunity_memory_by_id,
    list_opportunity_memory,
    STATUS_NEWLY_DISCOVERED,
    STATUS_RECURRING,
    STATUS_STRENGTHENING,
    STATUS_WEAKENING,
)
from .portfolio_watches import (
    add_watch,
    remove_watch,
    get_watch,
    list_watches,
    update_watch_snapshot,
    TARGET_ASIN,
    TARGET_KEYWORD,
    TARGET_NICHE,
    TARGET_CLUSTER,
)
from .copilot_research_memory import (
    save_session as save_copilot_session,
    get_session as get_copilot_session,
    list_sessions as list_copilot_sessions,
    link_sessions as link_copilot_sessions,
)
from .signal_results import (
    insert_signal_result,
    get_signal_result_latest,
)
from .opportunity_rankings import (
    insert_ranking,
    get_latest_ranking,
    get_latest_rankings,
)
from .persistence import (
    append_bsr_history,
    append_price_history,
    append_review_history,
    get_asin_by_id,
    get_asin_id,
    get_asins_metadata,
    get_bsr_history,
    get_price_history,
    get_product_metrics_by_asin_ids,
    get_review_history,
    insert_scoring_result,
    record_attempt,
    record_failure,
    record_success,
    should_skip_asin,
    upsert_asin,
    upsert_product_metrics,
)

__all__ = [
    "add_asin_relationship",
    "add_watchlist_item",
    "add_seed",
    "add_category_seed",
    "add_keyword_seed",
    "create_notification_rule",
    "create_saved_view",
    "create_watchlist",
    "create_user",
    "create_workspace",
    "create_workspace_api_key",
    "get_asin_by_id",
    "get_saved_view",
    "get_watchlist",
    "evaluate_rule",
    "get_notification_rule",
    "list_notification_rules",
    "list_saved_views",
    "list_watchlist_items",
    "list_watchlists",
    "remove_watchlist_item",
    "create_plan",
    "get_plan",
    "get_workspace_plan",
    "list_asins_by_workspace",
    "list_plans",
    "list_workspace_api_keys",
    "list_workspaces",
    "set_workspace_plan",
    "update_saved_view",
    "get_connection",
    "get_relationships_for_asin_ids",
    "get_users_for_workspace",
    "get_workspace",
    "get_asins_metadata",
    "get_enabled_seed_urls",
    "get_active_category_seed_urls",
    "get_active_keyword_seeds",
    "get_category_seed",
    "get_keyword_seed",
    "get_ready_keyword_seeds",
    "get_ready_category_seeds",
    "init_db",
    "list_relationships",
    "list_category_seeds",
    "list_keyword_seeds",
    "list_seeds",
    "persist_related_sponsored_candidates",
    "run_data_quality_checks",
    "run_retention_cleanup",
    "set_seed_enabled",
    "set_category_seed_active",
    "set_keyword_seed_active",
    "update_category_seed_scan",
    "update_keyword_seed_scan",
    "upsert_asin",
    "upsert_product_metrics",
    "append_bsr_history",
    "append_price_history",
    "append_review_history",
    "get_asin_id",
    "get_bsr_history",
    "get_trend_result_history",
    "get_trend_result_latest",
    "get_price_history",
    "get_product_metrics_by_asin_ids",
    "get_review_history",
    "insert_scoring_result",
    "record_attempt",
    "record_success",
    "record_failure",
    "check_quota",
    "check_quota_and_raise",
    "get_usage_summary",
    "get_usage_summary_for_workspace",
    "get_workspace_quota",
    "list_workspace_quotas",
    "record_usage",
    "set_workspace_quota",
    "QuotaExceededError",
    "get_billable_events_summary",
    "list_audit_logs",
    "record_audit",
    "record_billable_event",
    "record_usage_summary_billable",
    "dequeue_next",
    "enqueue_job",
    "get_job",
    "get_job_counts_for_workspace",
    "get_queue_metrics",
    "list_jobs",
    "mark_job_completed",
    "mark_job_failed",
    "run_job",
    "run_job_async",
    "schedule_retry_or_mark_failed",
    "should_skip_asin",
    "validate_workspace_api_key",
    "persist_trend_result",
    "TARGET_TYPE_ASIN",
    "TARGET_TYPE_CLUSTER",
    "save_cluster_cache",
    "get_cluster_cache",
    "get_cluster_cache_freshness",
    "invalidate_cluster_cache",
    "save_discovery_result",
    "get_discovery_result_latest",
    "get_discovery_results",
    "get_discovery_context_for_asin",
    "SOURCE_TYPE_CATEGORY",
    "SOURCE_TYPE_KEYWORD",
    "SOURCE_TYPE_GRAPH",
    "SOURCE_TYPE_AUTOMATED",
    "add_asin_keyword_edge",
    "add_asin_keyword_edges_bulk",
    "get_keywords_for_asin",
    "get_asins_for_keyword",
    "sync_edges_from_discovery_result",
    "SOURCE_KEYWORD_SCAN",
    "SOURCE_DISCOVERY_RESULT",
    "SOURCE_EXPANSION",
    "save_opportunity_alert",
    "list_opportunity_alerts",
    "set_opportunity_alert_read",
    "save_tenant_snapshot",
    "get_latest_snapshot",
    "get_snapshot_history",
    "save_workspace_intelligence_snapshot",
    "get_latest_workspace_intelligence_snapshot",
    "list_workspace_intelligence_snapshots",
    "get_workspace_configuration_row",
    "upsert_workspace_configuration_row",
    "save_autonomous_run_audit",
    "get_audit_for_run",
    "get_autonomous_audit_trail",
    "record_opportunity_seen",
    "get_opportunity_memory",
    "get_opportunity_memory_by_id",
    "list_opportunity_memory",
    "insert_signal_result",
    "get_signal_result_latest",
    "insert_ranking",
    "get_latest_ranking",
    "get_latest_rankings",
    "STATUS_NEWLY_DISCOVERED",
    "STATUS_RECURRING",
    "STATUS_STRENGTHENING",
    "STATUS_WEAKENING",
    "add_watch",
    "remove_watch",
    "get_watch",
    "list_watches",
    "update_watch_snapshot",
    "TARGET_ASIN",
    "TARGET_KEYWORD",
    "TARGET_NICHE",
    "TARGET_CLUSTER",
    "save_copilot_session",
    "get_copilot_session",
    "list_copilot_sessions",
    "link_copilot_sessions",
    "add_workspace_portfolio_item",
    "archive_workspace_portfolio_item",
    "get_workspace_portfolio_item_by_key",
    "get_workspace_portfolio_summary",
    "list_workspace_portfolio_items",
    "get_workspace_alert_preferences_row",
    "upsert_workspace_alert_preferences_row",
    "create_workspace_activity_event_row",
    "list_workspace_activity_events",
    "get_workspace_activity_summary",
]
